### ISSUE TITLE
Forestry previews are not working

### ISSUE THREAD

**Issue by mdcramer** [mdcramer/mdcramer.github.io#1]
When I click the "preview" icon in Forestry.io I am taken to a page that says, "Nothing to see here..."

In an email exchange with Sebastian in support at Forestry, he said:

> It looks like the site is previewing correctly, but unfortunately Forestry is unable to accurately detect the path/url of the post you're trying to preview.
> 
> If you strip the url to the base  https://YOUR-SITE-LOOKUP.preview.forestry.io/ you'll be able to see your site. 
> 
> However, it looks like your sites are not correctly building. I forked your repository and tried to run it locally but am running into a few errors.
> 
> `Error: File exists @ dir_s_mkdir - /Users/sebastian/git_repos/forestry-support/mdcramer.github.io/_site/deep-speeling-blog/index.html
>  Error: Run jekyll build --trace for more information.`
> 
> It looks like it has to do with the number of pages on one site (it looks like if you have more than 7 files in your deep-speeling-blog directory the site throws the above error). Do you run into this issue locally as well?

In a subsequent email he said:

> I clicked on your link (https://mdcramer.github.io/perceptron-magic-blog/the-perceptron-class/) but only got a 404 error. 
> 
> However, https://mdcramer.github.io/perceptron-magic-blog/ does work. That is in fact the issue. Your site doesn't build completely, once you go past 7 files in your theme it breaks for some reason. 
> 
> You usually are (of course) allowed to have more than 7 files in a directory this is likely an issue with the theme you're using and not with Forestry.
> 
> The preview issue is probably also related to the theme error or misconfiguration, hence Forestry is looking for the file in the right place but unfortunately since it is not being build can't find it.
> 
> For example if you navigate to pages -> index.html and preview that page you'll see that you can successfully preview your site.

This was back in January, but I recently tried again and it's still not working.

**Comment by onweru** [comment]
I fixed this to some extent; it will now show a preview link. Try it out and get a sense of what I mean by "to some extent"

**Comment by mdcramer** [comment]
Thank you, Weru! I'm not sure what you did, but now when I click the preview icon I'm taken to https://puiihnoasal1sa.preview.forestry.io/ which is a preview of the entire site.

I've played around with it a little bit, so what is the "to some extent?" The preview loads very slowly, even though it says "this won't take long." Also, it would appear that when I make a change on Forestry.io I have to re-load the preview (which I'm guessing rebuilds the site) and then navigate to the page I want to see. That's a bit of a pain.

Is there something else that I'm missing?

**Comment by onweru** [comment]
> When I click the preview icon I'm taken to https://puiihnoasal1sa.preview.forestry.io/ which is a preview of the entire site.

That's what I meant by to *"to some extent"*. Ideally, the preview ought to preview the exact page you're editing. Unfortunately, I have observed that my Jekyll sites exhibit this subpar behavior. My Hugo sites exhibit the desired behavior. I will reach out to the forestry team and see if they can steer me in the right direction.

> The preview loads very slowly, even though it says "this won't take long." ... That's a bit of a pain.

 Jekyll is significantly slow when generating a site.  I suppose there's a way we could configure forestry to only watch for changed files and perform incremental changes. I will look into it.

**Comment by mdcramer** [comment]
So, navigating back to the page isn't the end of the world; I'll just be using the preview feature less frequently, especially if I have to wait 15 seconds for the site to build each time.

I can see what Forestry is trying to accomplish, but I have to admit that I'm not blown away by it. I'm also clearly not a fan of Jekyll. I don't understand why Github would choose Jekyll, but then I'm not a fan of Github either! :-)

Anyway, great job with this and thank you. If you find any updates, please let me know.

**Comment by onweru** [comment]
> I'm also clearly not a fan of Jekyll.

Now that I have been working with Hugo more and more, I completely understand your concerns. Forestry really shines with Hugo. Hugo is dozens * faster than our beloved Jekyll also. Most of my projects now (80%) are in Hugo.

> I don't understand why Github would choose Jekyll, but then I'm not a fan of Github either! :-)
Jekyll is a child of Github in some way. Also it was the first static site generator to really work. For all its faults, it's still pretty popular. That said, it has lost massive ground to Hugo and I don't see how it will recover. Jekyll is based on Ruby which is single-threaded and slow. Hugo is based on golfing which allows multiple threads (concurrency). Hugo will marginalize Jekyll in the long-term.

> Anyway, great job with this and thank you.

You're most welcome

> If you find any updates, please let me know.

I certainly will
