### ISSUE TITLE
Math not rendering properly

### ISSUE THREAD

**Issue by mdcramer** [mdcramer/mdcramer.github.io#2]
The equation after the second paragraph of https://mdcramer.github.io/perceptron-magic-blog/the-perceptron-class/ has two problems:

1. It's not spanning the page.
2. The LaTeX command `\dots` is not properly being rendered as "..."

**Comment by mdcramer** [comment]
I tried `\cdots` and it didn't work. I must have done something else wrong. Thanks!

**Comment by onweru** [comment]
Ensure that you're not using `\\cdots`, instead, use `\cdots'

**Comment by mdcramer** [comment]
No, I used `\cdots`. Oh well. I'm must have made some other error. Anyway, it's clear that MathJax is not identical to LaTeX (I've been writing papers with Overleaf and have been using https://www.codecogs.com/latex/eqneditor.php), but I'm sure I can adjust.

**Comment by onweru** [comment]
I'm not really familiar with either. I just searched around and played with it on my local server 😃.
