### ISSUE TITLE
404 error with homepage link to GitHub

### ISSUE THREAD

**Issue by mdcramer** [mdcramer/mdcramer.github.io#4]
On the home page of https://mdcramer.github.io/ the "GitHub" link in the upper-right corner goes to https://github.com/mdcramer/mdcramer.github.io/tree/blog/_, which is a 404. It should just go to https://github.com/mdcramer.

On the pages for the different articles and blog posts, like https://mdcramer.github.io/deep-speeling-blog/, this link should go to the home page of the associated repo, like https://github.com/mdcramer/Deep-Speeling.

**Comment by onweru** [comment]
@mdcramer, the problem here was the underscore `_` at the end  of the url. I fixed it.

**Comment by mdcramer** [comment]
Fixed. Thank you!
